### PR TITLE
Add ability to change base layer map

### LINKED ISSUE #125: Remove or enable toggling of ever-present background state borders and state/city names?
In conversation with David Chang, it became clear that it is disrespectful to "suggest" the present day borders and names when viewing the land and indigenous nations from a historical perspective. Moreover, since one can always slide the time bar to the present to see present-day borders, it's reasonable to remove these borders and labels from the background so that the historic borders, tribes, and claims are not diminished by the presence of the present-day borders and labels.

If it is found to be desirable to show the present-day borders and labels when looking at historic times, then a compromise can be struck by enabling the toggle of these present-day borders and labels with a UI switch that is defaulted to off.

### PR DESCRIPTION
**Pull request by ohmec**
Fixes #125 

This gives us 6 base layer options, and changes the default to the most innocuous.

It also key maps `0` to `5` to toggle maps, or you can use the layer selector in the upper right corner.

Signed-off-by: Scott Johnson <sjcupertino@gmail.com>

### CODE REVIEW

**Comment by warrenjp** [comment]
Current zoomSettingMax is 15. I see that the maxZoom for the six backgrounds are, respectively, 13, 16, 16, 18, 9, 16. Based on these limitations, my leading choice for default background is 5: World. Closely behind is 0: Relief. I do not like 2: Paint any more. It's just all wrong. I do not like 1: Gray since it has text and doesn't show any land features. 

Thus, my conclusion is to move forward with 5: World and see how it passes (or not) the test of time.

**Comment by ohmec** [comment]
I'm mostly in agreement with you, except that `world` is quite dark for our current color model, and we'd have to do a fair amount of re-coloring to work around that. I'm removing gray and adding another one that I missed on first pass. It has faint borders but no labels. I'll call it `stamen` since it is another terrain. I'll push an update for this order:

`relief`, `stamen`, `world`, `physical` (wish it went to 15), `streets` (for those that want max labels), and `paint` (for whimsy, but yeah it isn't growing on me). Just FYI evidently `6` is already key mapped and I can't seem to override it, so how's that for a lame reason to stick to just 6 options.

**Comment by ohmec** [comment]
moving `stamen` down to 5th, the borders can be annoying at certain locations.

**Comment by ohmec** [comment]
@warrenjp I'm going to go ahead and merge this one as is because I think it is an important improvement over the default map of today. If you'd prefer to see a different list or other change (ie. I'm not sure having the layer switcher in the upper right is the right place) please file an issue.

**Pull request merged**
