### PR TITLE
first attempt to incorporate data from native-land.ca

### PR DESCRIPTION
**Pull request by warrenjp**
Signed-off-by: Warren Packard <warrenjp@gmail.com>

I am going to make this a draft pull request because I am not ready to push this out to production. We need to figure out a number of things before doing so, including:

1) how do we improve the performance of all this new data?
2) how do we want the fill and border colors to work?
3) how do we want to make all the overlapping features easier to discern?
4) how do we make all of this new data dynamic? Among other things, and perhaps first on the list, we need to show how all of these nations transform and move, over time, to the reservations where they exist today.

This is the first effort to incorporate the rich data provided by native-land.ca. Rather than pull in the native-land data via API, I copied over their Territories DB into a new file called ohmec_data_nl.js. This precludes us from having to pull over the data in real-time which would take some time to accomplish. The trade-off is that we need to proactively pull over the native-lands.ca data every week or two and push it to upstream. This will eventually become a chore and we may decide at that time to pull directly from their API. For the time being, as we're developing this functionality, the current methodology is just fine (and let's us put off figuring out how to fetch data in real-time).

This PR addresses issue #129.

### CODE REVIEW

**Comment by ohmec** [comment]
Excellent (spoken theoretically, I haven't visualized it just yet), and leaving a few thoughts. Thanks for engaging this. Indeed it sparks decision time.

> 1. how do we improve the performance of all this new data?
Again, I haven't looked at it yet, but I was experimenting with a "definition reducer" script that I have around to play with, if need be. It reduces the coordinate count in a programmatic way to keep most of the general shape but reducing some of the fine details, since generally we don't care. For example, you can give it a distance (say 1km) and it will remove extraneous too-detailed coordinates. We could also consider reducing the number of significant digits. I'll return after playing with this to see if these tricks might be useful.

> 2. how do we want the fill and border colors to work?
I think this will be important to get "pretty correct". I recommend something like a common color for language groups, if that data exists, so it doesn't look so psychedelic, but still retains some ability to show the diversity of the dataset

> 3. how do we want to make all the overlapping features easier to discern?
I think if we get 2. above pretty clean, then perhaps it won't matter so much

> 4a. how do we make all of this new data dynamic? 
The question back at you is: do we have dynamic data? Does the original API provide a time when this was the source of truth? Or are these polygons a superset of the full range throughout their known history? If the source API doesn't have the information, then I'd be leery of being the ones to put it in there. However, it would be super cool to be the ones to give them the ability to visualize it if they can't today in their interface

> This precludes us from having to pull over the data in real-time which would take some time to accomplish.
There are free scripting features within Github we could employ that could automate this. In prior projects I've seen weekly-run scripts that at least take some of the burden off, even if they can't automate the Pull Requests. Basically what I'm saying is there are tradeoffs we could consider to approximate this real time update. But another question to you: how often do they change?

> For the time being, as we're developing this functionality, the current methodology is just fine
Agreed

Thanks again, I'll check this out soon.

**Comment by ohmec** [comment]
Just FYI when I check it out I get an error: `ohmec.js:780 Uncaught ReferenceError: dataNL is not defined at ohmec.js:780`. I think I can fix it locally, just letting you know.

**Comment by ohmec** [comment]
> Just FYI when I check it out I get an error: `ohmec.js:780 Uncaught ReferenceError: dataNL is not defined at ohmec.js:780`. I think I can fix it locally, just letting you know.

Or ... maybe not. Looks like you forgot at add `ohmec_data_nl.js`

**Comment by ohmec** [comment]
OK, now that I can see it all, I have a few more comments.

a) I really like how you've done the addition, keeping for the most part their database, then post-processing it to conform
b) sadly, the problem isn't too many coordinate points. they've kept it pretty "svelte". I tried reducing to 4 significant digits and it didn't help. I also removed the occasional third dimensional coordinate (z) that sometimes is used, in case that was confusing Leaflet. But no noticeable improvement. I'm sure we could trim the coordinates a bit and not lose geographic definition, but I doubt it would save much
c) noticeably the performance is only a problem when they're on the screen, and don't affect it when not
d) load time isn't too bad, just pan and zoom primarily, and timeline slider when moving into or out of their time space.
e) This would only get worse with dynamic movement.
f) I tried an experiment to revert them to borderless just to see the performance impact. Doesn't really help. Helps the readability, but loses the important borders
g) I tried another experiment turning down the `fillOpacity` to 0.1, and it helped readability. This might be a useful tradeoff.

Screen Shot 2021-12-06 at 3 02 55 PM

h) we could consider a layer selection like we have for background layers to select and deselect western and indigenous features. Not sure yet how I feel about that from a fairness perspective. In theory it is equally fair, but feels like "hey let's just turn this stuff off"

I'll do a few measurements of the precision of the regions and see if there is any hope for performance improvements there, but I kind of doubt it, they don't look overbearing akin to a full rendered shapefile.

Great work @warrenjp !!

**Comment by ohmec** [comment]
Oh, final note. This could just be a leaflet thing. I could try and figure out what tool they're using under the hood and we could port to that.

**Comment by ohmec** [comment]
> I'll do a few measurements of the precision of the regions and see if there is any hope for performance improvements there, but I kind of doubt it, they don't look overbearing akin to a full rendered shapefile.

Reducing the precision to about 10 miles didn't help performance much, even though it reduced the file size by about half. Tells me that Leaflet is just struggling with the feature count. It did make the borders look much more angular and janky though!

**Comment by ohmec** [comment]
OK, I took a new approach, and I'm pretty happy with the results. We already know that we're going to struggle with a world-wide database, and have started down the approach of breaking into continents. (This is going to be challenging for Eastern Europe as it blends with Asia, The Middle East, and regions like Panama that straddle.) So I changed your algorithm to only include those tribes that are in North America, to be in kind with the rest of the data there. That equates to 44% of the data. With that much included, the performance is quite reasonable. Not ideal, and certainly still problematic if/when we get some form of animation. But definitely doable. With that change and with the default opacity for indigenous to `0.1` to avoid psychedelic overdose I'm quite happy with the look of it.

Re the different regions, I like the idea of clipping that way with a layer controller rather than clipping based upon western vs native.

Now this spurs a few more thoughts:

1. a la #133, I definitely prefer the coloring information to be part of the database, I'll move in that direction, though slightly different than this one does
2. I do wish the colors indicated language group or something. Perhaps that is something we could sniff out in a different way
3. The indigenous names in their default script (nb Dakeł Keyoh (ᑕᗸᒡ ᗲᘏᑋ)) are supercool, but it would be good to have a uniform way to render them a la `AmericanizedName\n(IndigenousRendering)` or something like that
4. My OCD really wants to spend time improving the label location, but defeats the automation
5. Ones like Cree are unfairly large, but label OCD comes to mind
6. I don't really love the color palette they've chosen, maybe we can inquire as to how they came up with that and if there is a better way to approach it (similar to 1. above)
7. They do a weird thing when it comes to multiple polygons. Rather that using a `MultiPolygon` they connect two with a diagonal line, which looks a little goofy.
8. Repeating from above, let's find out the answer if we can to: "do we have dynamic data? Does the original API provide a time when this was the source of truth? Or are these polygons a superset of the full range throughout their known history?"

**Comment by ohmec** [comment]
I also recommend this change to line 700 of `ohmec.js`:

```javascript
      f.properties["source"]=f.properties["description"];
```

That takes it directly to the indigenous page.

We should also consider a popup the first time entering this content like what they have upon first entering, plus combine an attribution to their page:

```
Native Land Disclaimer

This map does not represent or intend to represent official or legal boundaries of any
Indigenous nations. To learn about definitive boundaries, contact the nations in question.

Also, this map is not perfect -- it is a work in progress with tons of contributions from
the community. Please send us fixes if you find errors.

If you would like to read more about the ideas behind Native Land or where we are
going, check out the blog. You can also see the roadmap.
```

**Comment by warrenjp** [comment]
> OK, I took a new approach, and I'm pretty happy with the results. We already know that we're going to struggle with a world-wide database, and have started down the approach of breaking into continents. (This is going to be challenging for Eastern Europe as it blends with Asia, The Middle East, and regions like Panama that straddle.) So I changed your algorithm to only include those tribes that are in North America, to be in kind with the rest of the data there. That equates to 44% of the data. With that much included, the performance is quite reasonable. Not ideal, and certainly still problematic if/when we get some form of animation. But definitely doable. With that change and with the default opacity for indigenous to `0.1` to avoid psychedelic overdose I'm quite happy with the look of it.

Awesome! How can I incorporate all of these enhancements that you made?

> Re the different regions, I like the idea of clipping that way with a layer controller rather than clipping based upon western vs native.

I completely agree.

And thanks for the additional thoughts below... Definitely got to shelve your OCD or else you'll be spending 

> Now this spurs a few more thoughts:
> 
> 1. a la [[database] consider moving geo_features elements into JSON database #133](https://github.com/ohmec/ohmec/issues/133), I definitely prefer the coloring information to be part of the database, I'll move in that direction, though slightly different than this one does
> 2. I do wish the colors indicated language group or something. Perhaps that is something we could sniff out in a different way
> 3. The indigenous names in their default script (nb Dakeł Keyoh (ᑕᗸᒡ ᗲᘏᑋ)) are supercool, but it would be good to have a uniform way to render them a la `AmericanizedName\n(IndigenousRendering)` or something like that
> 4. My OCD really wants to spend time improving the label location, but defeats the automation
> 5. Ones like Cree are unfairly large, but label OCD comes to mind
> 6. I don't really love the color palette they've chosen, maybe we can inquire as to how they came up with that and if there is a better way to approach it (similar to 1. above)
> 7. They do a weird thing when it comes to multiple polygons. Rather that using a `MultiPolygon` they connect two with a diagonal line, which looks a little goofy.
> 8. Repeating from above, let's find out the answer if we can to: "do we have dynamic data? Does the original API provide a time when this was the source of truth? Or are these polygons a superset of the full range throughout their known history?"

**Comment by ohmec** [comment]
Here are my proposed changes to `geo_features.js`:

```
> git diff geo_features.js 
diff --git a/geo_features.js b/geo_features.js
index 1e29648..f6f57a8 100644
--- a/geo_features.js
+++ b/geo_features.js
@@ -49,8 +49,9 @@ function featureStyle(feature) {
       borderless = false;  // now set to false with incorporation of data from native-land.ca
     }
     strokeColor  = '#a00000';
-    strokeWeight = 1.5;
+    strokeWeight = 1;
     strokeDash   = '1';
+    fillOpacity  = 0.1;
     fillColor    = feature.properties["color"];
   } else if(entity1name == 'USA' && entity2type == 'secessionist') {
     strokeColor  = '#0000a0';
@@ -220,7 +221,7 @@ function getFeatureFont(feature) {
 
   if(entity1name == 'Indigenous' && entity2type == 'tribe') {
     fontchoice = 3;
-    fontcolor  = "#c00000";
+    fontcolor  = "#105010";
   }
 
   if(feature.geometry.type === "Point") {
```

**Comment by ohmec** [comment]
This one in `ohmec.js` is kind of lengthy, sorry about that. Also, I recommend you don't need to change `ohmec_data_na.js`, but algorithmically remove its indigenous members if including this new database. We can discuss how to do that if it is not obvious.

```
> git diff ohmec.js
diff --git a/ohmec.js b/ohmec.js
index 258d434..928c172 100644
--- a/ohmec.js
+++ b/ohmec.js
@@ -670,6 +670,7 @@ function geo_lint(dataset) {
 // augment native-lands metadata with enhanced geojson metadata so it meets ohmec baseline requirements
 function transform_dataNL(dataset) {
   let id_set = new Set();
+  let featureList = [];
   if(dataset.type !== "FeatureCollection")
     throw "expected dataset type === FeatureCollection, got " + dataset.type;
   if("features" in dataset) {
@@ -680,58 +681,80 @@ function transform_dataNL(dataset) {
       if(id_set.has(f.id)) {
         throw "got duplicate dataset ID " + f.id;
       }
-      id_set.add(f.id);
-      fHash[f.id] = f;
-      if("properties" in f) {
-        let p = f.properties;
-        for(let required of ["entity1type", "entity1name", "fidelity",
-            "startdatestr", "enddatestr"]) {
-          if(!(required in p)){
-            f.properties["entity1type"]="nation";  // these are all "magic numbers" and should be made into const
-            f.properties["entity1name"]="Indigenous";
-            f.properties["entity2type"]="tribe";
-            f.properties["entity2name"]=f.properties["Name"];
-            if(typeof f.properties["entity2name"] === "undefined") {
-              f.properties["entity2name"]=" ";
+      // make sure this feature is in North America before adding
+      let bounds = L.polygon(f.geometry.coordinates).getBounds();
+      // roughly compare against Panama in the south (7N) and Greenland on the east (21W)
+      // geoJson has order [lon,lat] so oddly this flips the definitions of south and east
+      let boundsE = bounds.getSouth();
+      let boundsW = bounds.getNorth();
+      let boundsS = bounds.getWest();
+      let boundsN = bounds.getEast();
+      let is_na = (boundsE <= -21) && (boundsS >= 7);
+      // there are still some in NW South America, clip those too
+      if(is_na && (boundsN < 12.6) && (boundsW > -77)) {
+        is_na = false;
+      }
+      if(is_na) {
+        id_set.add(f.id);
+        fHash[f.id] = f;
+        if("properties" in f) {
+          let p = f.properties;
+          for(let required of ["entity1type", "entity1name", "fidelity",
+              "startdatestr", "enddatestr"]) {
+            if(!(required in p)){
+              f.properties["entity1type"]="nation";  // these are all "magic numbers" and should be made into const
+              f.properties["entity1name"]="Indigenous";
+              f.properties["entity2type"]="tribe";
+              f.properties["entity2name"]=f.properties["Name"];
+              if(typeof f.properties["entity2name"] === "undefined") {
+                f.properties["entity2name"]=" ";
+              }
+              f.properties["fidelity"]=2;
+              f.properties["startdatestr"]="700";
+              f.properties["enddatestr"]="1768";
+              f.properties["source"]=f.properties["description"];
             }
-            f.properties["fidelity"]=2;
-            f.properties["startdatestr"]="700";
-            f.properties["enddatestr"]="1768";
-            f.properties["source"]="https://native-land.ca/";
           }
-        }
-        p.startDate = str2date(p.startdatestr,false);
-        if(p.enddatestr == 'present') {
-          p.endDate = today;
+          p.startDate = str2date(p.startdatestr,false);
+          if(p.enddatestr == 'present') {
+            p.endDate = today;
+          } else {
+            p.endDate = str2date(p.enddatestr,true);
+          }
+          let fid = p.fidelity;
+          if(fid < 1 || fid > 5) {
+            throw "fidelity for " + f.id + " should be between 1 (lowest) and 5 (highest), got " + fid;
+          }
+          timelineDateMinDefault = dateMin(timelineDateMinDefault, p.endDate);
+          timelineDateMaxDefault = dateMax(timelineDateMaxDefault, p.startDate);
+          datesOfInterest.push(p.startDate);
+          polygonCount += 1;
+          if("animateTo" in p) {
+            animationHash[f.id] = p.animateTo;
+          }
         } else {
-          p.endDate = str2date(p.enddatestr,true);
-        }
-        let fid = p.fidelity;
-        if(fid < 1 || fid > 5) {
-          throw "fidelity for " + f.id + " should be between 1 (lowest) and 5 (highest), got " + fid;
+          throw "no properties in feature " + f.id;
         }
-        timelineDateMinDefault = dateMin(timelineDateMinDefault, p.endDate);
-        timelineDateMaxDefault = dateMax(timelineDateMaxDefault, p.startDate);
-        datesOfInterest.push(p.startDate);
-        polygonCount += 1;
-        if("animateTo" in p) {
-          animationHash[f.id] = p.animateTo;
-        }
-      } else {
-        throw "no properties in feature " + f.id;
-      }
-      if("geometry" in f) {
-        let g = f.geometry;
-        if((g.type !== "Polygon") && (g.type !== "MultiPolygon") && (g.type !== "Point")) {
-          throw "feature " + f.id + " should have geometry of Polygon, MultiPolygon or Point, got " + g.type;
+        if("geometry" in f) {
+          let g = f.geometry;
+          if((g.type !== "Polygon") && (g.type !== "MultiPolygon") && (g.type !== "Point")) {
+            throw "feature " + f.id + " should have geometry of Polygon, MultiPolygon or Point, got " + g.type;
+          }
+        } else {
+          throw "no geometry in feature " + f.id;
         }
-      } else {
-        throw "no geometry in feature " + f.id;
+        featureList.push(f);
       }
     }
   } else {
     throw "no features in dataset"
   }
+  return featureList;
 }
 
@@ -777,8 +800,8 @@ function prepare_animations() {
 }
 
 geo_lint(dataNA);
-transform_dataNL(dataNL);
-dataNA.features = dataNA.features.concat(dataNL.features);
+let dataNLNA = transform_dataNL(dataNL);
+dataNA.features = dataNA.features.concat(dataNLNA);
 prepare_animations();
```

**Comment by ohmec** [comment]
> 8. Repeating from above, let's find out the answer if we can to: "do we have dynamic data? Does the original API provide a time when this was the source of truth? Or are these polygons a superset of the full range throughout their known history?"

Still would really love to know the answer to this one. Do you know, and if not, shall we discuss with someone on that project?

**Comment by warrenjp** [comment]
PR abandoned due to incorporation into PR #160

**Pull request closed without merging**
