### PR TITLE
Simple attempt at double-line labels

### PR DESCRIPTION
**Pull request by ohmec**
Addresses #20 

This does a simple implementation of using `\n` to indicate the preference for a double-line label. 

In this example, `entity2name = "Nuwuvi\n(Southern Paiute)"`

Screen Shot 2021-10-25 at 3 50 17 PM

In the same PR, using this feature for land grants (will let @warrenjp consider for native tribes), and fixing #126 by making land grants transparent with the text towards the populated side.

Signed-off-by: Scott Johnson <sjcupertino@gmail.com>

### CODE REVIEW

**Comment by ohmec** [comment]
There are several PRs lingering, which I don't like since it makes merging tough. We need to decide on these, so weigh in @warrenjp. I'm hoping to finalize tomorrow (Wednesday). Here are my thoughts on this one:

I think this can only be useful, and doesn't get in the way. I'll have to find a way to formalize the offset though, it doesn't work beautifully in all cases.

**Comment by warrenjp** [comment]
I agree, this is a useful feature and should be implemented.

It appears that the challenge with the spacing occurs with Arced text when the top line is longer than the bottom line. If this is indeed the case, what about establishing the spacing based on whether or not the first line is longer than the second line. Of course, there could be more than two lines, so this should be made an algorithm that can adjust the spacing based on which of the N lines is longest. I don't think that there are any inherent spacing issues for non-Arced text.

Given that the spacing challenge will only show up in rare circumstances, I would go ahead and merge this feature right now and create a new issue for dealing with the y-spacing for arced multi-line text.

**Comment by ohmec** [comment]
Going back to draft, failing on merge

**Comment by ohmec** [comment]
Rebased successfully. Removed the Paiute example, but used the land grants as `\n` examples, and killing two birds with one stone here, fixing #126 too by making land grants completely transparent, and moving the text to where settlements occurred. PTAL.

@warrenjp once this is merged, feel free to use it for long-named tribes (with parenthetical translations) to allow their text to be larger as appropriate. Your discretion.

**Pull request merged**
