### PR TITLE
Showing examples of potential points of interest

### PR DESCRIPTION
**Pull request by ohmec**
This is a draft pull request showing potential for using Point geometries as points of interest. In this example, there are three types of points declared, using `entity1type`: `poi` (generic point of interest), `settlement`, and `battle`. They each have a rendered icon placed at the given point, and use `entity1name` to create a label.

Addresses #103

A few other notes about this code:

* the size of the icon and default label size is intentionally "intimate" in the sense that it only shows well for zooms like 10 or so. It seems you wouldn't want something like a battle marker to show up when zooming out to the whole world
* the native Leaflet point marker is neutered by making it opacity of 0.0. AFAICT any other neutering loses its ability to be selected. This was done since otherwise the Point marker is always the same size no matter the zoom
* the icons are manual SVG; there's likely a way to import an SVG file instead
* this adds a new feature to the GeoJSON to help with labeling: `labelJustify`, with legal values `left` (default for Point), `right`, `above`, and `below`. The default for other geometries is `middle`.
* other label modifiers like X, Y, Rotate, Scale, etc still work
* the default bounding box for a label is 1 degree by 1 degree. arbitrary but allows for enough text
* the startDate and endDate elements still apply, so we'd need a concept of when to "end" a point of interest
* choosing a different font and font color, don't love it, but just choosing one of the researched list

Here's an example showing the three types, and three types of `labelJustify`

Screen Shot 2021-10-22 at 4 31 19 PM

Signed-off-by: Scott Johnson <sjcupertino@gmail.com>

### CODE REVIEW

**Comment by ohmec** [comment]
There are several PRs lingering, which I don't like since it makes merging tough. We need to decide on these, so weigh in @warrenjp. I'm hoping to finalize tomorrow (Wednesday). Here are my thoughts on this one:

I'm inclined to push these forward. We can decide if we want to use them sparingly, or create a guideline for when to use them so as to not clutter up the map. But having the option is a good thing I think, and improves over the standard Point.

**Review by warrenjp — APPROVED** [review]
Looks good. Parameters make sense and maintains ease of use/configuration.

**Comment by ohmec** [comment]
> Looks good. Parameters make sense and maintains ease of use/configuration.

Thanks, I'll do the more thorough job of documenting and clean up the code and get this one in.

**Comment by ohmec** [comment]
The documentation for Points of Interest has been updated. I did so in Suggesting Mode just so it was more obvious where the changes are located. Feel free to make comments, and I'll apply the changes once it looks good. Note that each of the pending PRs might have modifications to the documentation (eg. two-line entity names), but I'll do so in conjunction with each of those PRs.

[Pinned link to doc](https://docs.google.com/document/d/15D9t61Y1WYYH02BuIp3C8InJD40L19uHIcPNDfNv0Bk).

**Comment by warrenjp** [comment]
@ohmec The documentation looks great.

**Comment by ohmec** [comment]
> @ohmec The documentation looks great.

👍

**Comment by ohmec** [comment]
Cleaned this up, including using icon files rather than drawn SVG. Converting from draft to "real".

**Review by warrenjp — APPROVED** [review]

**Pull request merged**
