### PR TITLE
Try to improve performance with multiple HTML pages

### LINKED ISSUE #208: [webpage] consider multiple index.html
At the moment, all databases are brought into `index.html` in order to select between the various ones (NA, NL, Cherokee, AA, Europe/Viking). This has the benefit of unifying all into one place, but the downside of requiring a larger memory footprint when only one database is needed. This issue is a request to investigate having multiple `.html` files, where each is tied with a database (ie. `index_na.html`, `index_aa.html`, etc). The goal would be to do it without having to recreate all of the ancillary web text, though that might not be possible without switching to something like `.php`.

### PR DESCRIPTION
**Pull request by ohmec**
Fixes #208 

This breaks `index.html` in to multiple pages in order to hopefully improve readability as well as performance.

Signed-off-by: Scott Johnson <sjcupertino@gmail.com>

### CODE REVIEW

**Comment by ohmec** [comment]
Since this is a pretty big change to the user viewpoint, it would be good to get a second opinion from @warrenjp . Take your time.

**Comment by ohmec** [comment]
Updated to also handle "old style" study parameters, such as `index.html?cherokee`. These now get directed to the appropriate webpage (ie. `index_cherokee.html` in this case)

**Comment by warrenjp** [comment]
I suggest changing the word "peoples" to "nations" in the opening text in index_cherokee.html

**Review by warrenjp — APPROVED** [review]
Approved, but note that I made a number of comments suggesting minor, but not blocking, changes.

**Comment by ohmec** [comment]
I have address several of the comments, all but the "Advance" one. I'm not sure I like `Continuous +`, though I agree we can do better than `Advance`. I'll file an issue.

Note that your suggestion spurred me to test the feature of adding hyperlinks to popup text, which works nicely. Good suggestion @warrenjp .

**Pull request merged**
